[package]
name = "genetic-sudoku"
version = "0.1.0"
edition = "2021"
authors = ["Eric Wohltman <eric.wohltman@gmail.com>", "Bart Massey <bart@cs.pdx.edu>"]
repository = "http://github.com/ewohltman/genetic-sudoku"
keywords = ["sudoku", "solver", "genetic algorithms"]
categories = ["Algorithms", "Games"]
description = "Genetic Algorithm Sudoku solver"
license-file = "LICENSE"

[dependencies]
arrayvec = "0.7"
rayon = "1.5"
rand = "0.8"
clap = "2.34.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sudoku"
harness = false
