[package]
name = "genetic-sudoku"
version = "0.1.0"
edition = "2021"
authors = ["Eric Wohltman <eric.wohltman@gmail.com>", "Bart Massey <bart@cs.pdx.edu>"]
repository = "https://github.com/ewohltman/genetic-sudoku"
keywords = ["sudoku", "solver", "genetic algorithms"]
categories = ["Algorithms", "Games"]
description = "Genetic Algorithm Sudoku solver"
license-file = "LICENSE"

[dependencies]
arrayvec = "0.7"
clap = "2.34"
rayon = "1.5"
rand = "0.8"
rand_pcg = "0.3"
static_assertions = "1.1"

[dev-dependencies]
criterion = "0.3"

[profile.release]
debug = 1

[[bench]]
name = "sudoku"
harness = false
