[package]
name = "genetic-sudoku"
version = "0.1.0"
edition = "2021"
repository = "http://github.com/ewohltman/genetic-sudoku"
keywords = ["sudoku", "solver", "genetic algorithms"]
categories = ["Algorithms", "Games"]
description = "Genetic Algorithm Sudoku solver"
license-file = "LICENSE"

[dependencies]
arrayvec = "0.7.2"
bencher = "0.1.5"
rayon = "1.5.1"
rand = "0.8.4"

[[bench]]
name = "sudoku"
harness = false
