allowed-duplicate-crates = [
    "bitflags",
    "cpufeatures",
    "getrandom",
    "hashbrown",
    "itertools",
    "r-efi",
    "rand",
    "rand_core",
    "syn",
    "thiserror",
    "thiserror-impl",
]
