name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run fmt
        run: make fmt
      - name: Run clippy
        run: make clippy
      - name: Run tests
        run: make test
      - name: Run benchmarks
        run: make bench
      - name: Build binary
        run: make build
